FROM ubuntu:16.04
MAINTAINER omenia@omenia.fi
RUN apt-get update \
    && apt-get install -y iputils-ping traceroute net-tools apache2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
EXPOSE 80
ENTRYPOINT ["apache2ctl"]
CMD ["-D", "FOREGROUND"]