version: '3'
services:
  web:
    build: ./helloserver
    ports:
      - "5000:5000"
    volumes:
      - ./helloserver:/app
  redis:
    image: "redis:alpine"
  test:
    build: ./test
    volumes:
      - ./test:/test
